artifacts_root: artifacts

ingestion:
  root_dir: artifacts/data/
  download_url: "masoudnickparvar/brain-tumor-mri-dataset"
  raw_data_dir: artifacts/data/raw/
  extracted_data_dir: artifacts/data/extracted/

cleaning:
  root_dir: artifacts/clean/data
  source_data_dir: artifacts/data/raw

transformation:
  root_dir: artifacts/transform
  source_data_dir: artifacts/clean/data
  class_mode: categorical
  saved_train_gen_path: artifacts/transform/train_gen.npy
  saved_val_gen_path: artifacts/transform/val_gen.npy
  saved_test_gen_path: artifacts/transform/test_gen.npy

model_trainer:
  root_dir: artifacts/trainer
  model_path: artifacts/trainer/model.keras
  train_gen_path: artifacts/transform/train_gen.npy
  val_gen_path: artifacts/transform/val_gen.npy
  mlflow_uri: file:./mlruns
  experiment_name: NeuroScanBrainTumor

evaluation:
  root_dir: artifacts/evaluation
  test_gen_path: artifacts/transform/test_gen.npy
  model_file: artifacts/trainer/model.keras
  metrics_file_path: artifacts/evaluation/metrics.json
  confusion_matrix_plot_path: artifacts/evaluation/confusion_matrix.png
  mlflow_uri: file:./mlruns
  experiment_name: NeuroScanBrainTumor